### ISSUE TITLE
Optional arguments have no default values.

### ISSUE THREAD

**Issue by maybelinot** [ares/pruby#1]
@ares @iNecas I think that it wouldn't be worse to make [this sentence](https://github.com/ares/pruby/blob/master/ulohy/e03/zadani.txt#L18-L19) a bit more proper..

**Comment by ares** [comment]
It was meant in a way, that it except 3 to 5 arguments. Those three mandatory are name, max rear gear, max front gear. Maximums mean the limit which can't be shifted above. There are 2 more optional arguments, color and size of wheel. Does it make more sense now? If yes, could you please provide a sentence, that would be clearer?

**Comment by maybelinot** [comment]
Yeah, but it just confused me in the way of difference between `color` and `wheel_size`, since default color is not mentioned there I suppose that I'll need to put color like `*color` to list of arguments, if this is how it was conceived by you then everything is OK!

Not a big deal actually, but maybe it could help someone like me =)

**Comment by ares** [comment]
Color default was not specified, so I intended `color=nil`. I'll change the sentence for future use, I admit it's not clear. Thanks for the report.

**Comment by ares** [comment]
Fixed via https://github.com/ares/pruby/commit/47bcbd13f21449ad0d17b4934e1956cf4a897190
